
# Site settings
title: Inguanez Remy
email: remy.inguanez@laplateforme.io
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  remy-inguanez
permalink: :title

# Build settings
markdown: kramdown
